apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacy-deployment
  labels:
    app: spacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacy
  template:
    metadata:
      labels:
        app: spacy
    spec:
      containers:
      - name: spacy
        image: gcr.io/norwegian-language-bank/spacy:a098b230-45a8-4534-91b6-ae42e7f2eea0
        command: [ "/bin/bash" ]
        args: [ "-c", "streamlit run pos.py --server.port 8501 --server.baseUrlPath /spacy --browser.gatherUsageStats=False"]
        ports:
        - containerPort: 8501
        resources:
          limits:
            cpu: 1
            ephemeral-storage: 256Mi
            memory: 6Gi
          requests:
            cpu: 1
            ephemeral-storage: 256Mi
            memory: 6Gi